""" Stitch .gui files together for Machines & Robot Expansion Continued """
__author__ = '0xRetro (Openly Retro)'
__license__ = 'GPLv3'

import os

from mre_code_tools.pipeline.mre_common_vars import (
    BUILD_FOLDER,
    GUI_FOLDER,
    sanity_check,
)
HERE = os.getcwd()
CODE_TOOLS_PATH = os.path.join(
    HERE, 'mre_code_tools'
)
TEMPLATE_FOLDER = os.path.join(
    HERE,CODE_TOOLS_PATH,
    'templates'
)
COUNCILOR_FOLDER = os.path.join(
    HERE,CODE_TOOLS_PATH,
    'templates','councilor_editor'
)
core_gui_location = os.path.join(
    HERE, 'interface', 'xvcv_mdlc_core_modifying_customgui.gui'
)
leader_gui_location = os.path.join(
    HERE, 'interface', 'xvcv_mdlc_leader_making_customgui.gui'
)

core_stitch_order = [
    os.path.join(TEMPLATE_FOLDER, 'core_modifying', 'core_modifying_gui_1.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_core_modifying_official_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'core_modifying', 'core_modifying_gui_2.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_core_modifying_scientist_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'core_modifying', 'core_modifying_gui_3.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_core_modifying_commander_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'core_modifying', 'core_modifying_gui_4.txt')
]

leader_stitch_order = [
    os.path.join(TEMPLATE_FOLDER, 'leader_making', 'leader_making_gui_1.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_leader_making_official_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'leader_making', 'leader_making_gui_2.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_leader_making_scientist_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'leader_making', 'leader_making_gui_3.txt'),
    os.path.join(BUILD_FOLDER, '86_mre_autogenerated_leader_making_commander_gui.txt'),
    os.path.join(TEMPLATE_FOLDER, 'leader_making', 'leader_making_gui_4.txt')
]

councilor_file_template = "oxr_mdlc_councilor_editor_{node}_customgui.gui"
councilor_closing = os.path.join(
    TEMPLATE_FOLDER,'councilor_editor','editor_close.txt'
)

def stitch_gui_files():
    with open(core_gui_location, "w", encoding="utf8") as gui_file:
        for stitch_source in core_stitch_order:
            with open(stitch_source, "r") as stitch_file:
                gui_file.write(
                    stitch_file.read()
                )
    print("Core-Modifying GUI stitched (we hope)")
    
    with open(leader_gui_location, "w", encoding="utf8") as gui_file:
        for stitch_source in leader_stitch_order:
            with open(stitch_source, "r") as stitch_file:
                gui_file.write(
                    stitch_file.read()
                )
    print("Leader-making GUI file stitched (we hope)")

    for councilor in [
        'cognitive','growth','legion','regulatory'
    ]:
        councilor_gui_file = councilor_file_template.format(
            node=councilor
        )
        gui_file_location = os.path.join(
            HERE,'interface',councilor_gui_file
        )
        with open(gui_file_location, "w",encoding="utf8") as gui_file:
            gui_header = os.path.join(
                TEMPLATE_FOLDER,'councilor_editor',f"{councilor}_gui_1.txt"
            )
            traits_code = os.path.join(
                BUILD_FOLDER,f"30_oxr_mdlc_councilor_editor_{councilor}_gui_code.txt"
            )
            with open(gui_header) as gui_header_file:
                gui_file.write(gui_header_file.read())
            with open(traits_code) as traits_code_file:
                gui_file.write(traits_code_file.read())
            with open(councilor_closing) as gui_footer_file:
                gui_file.write(gui_footer_file.read())
        print(f"Wrote councilor editor file for {councilor} node (we hope)")


if __name__ == "__main__":

    print("0xRetro Machine & Robot Expansion Data Tools")
    print("GUI file stitcher v1.0")
    sanity_check()
    stitch_gui_files()
