l_simp_chinese:
 xvcv_mdlc_abyss_access_possible.message.off: "§Y深渊§!洞开通知：§R关闭§!"
 xvcv_mdlc_abyss_access_possible.message.on: "§Y深渊§!洞开通知：§G开启§!"
 xvcv_mdlc_civic_assimilating_swarm.message.off: "§Y$xvcv_mdlc_civic_assimilating_swarm$§!国民理念通知：§R关闭§!"
 xvcv_mdlc_civic_assimilating_swarm.message.on: "§Y$xvcv_mdlc_civic_assimilating_swarm$§!国民理念通知：§G开启§!"
 xvcv_mdlc_config.1.1.off: "物种转化（机器人→机械）：§R关§!"
 xvcv_mdlc_config.1.1.on: "物种转化（机器人→机械）：§G开§!"
 xvcv_mdlc_config.1.2.off: "物种转化（机械→机器人）：§R关§!"
 xvcv_mdlc_config.1.2.on: "物种转化（机械→机器人）：§G开§!"
 xvcv_mdlc_config.1.3.off: "物种合并：§R关§!"
 xvcv_mdlc_config.1.3.on: "物种合并：§G开§!"
 xvcv_mdlc_config.1.4.off: "自动人口迁移：§R关§!"
 xvcv_mdlc_config.1.4.on: "自动人口迁移：§G开§!"
 xvcv_mdlc_config.1.desc: "本模组提供了帮助玩家游玩的实用功能。您可以在这一页打开或关闭这些功能。\n\n机器人→机械物种的转化§Y每年§!进行一次，只在§B机械智能国家§!进行。\n机械→机器人物种的转化§Y每年§!进行一次，只在§G合成飞升国家§!进行。\n\n物种合并会把被转化物种并入我们的创始物种，并将我们所有的机械和机器人物种都变成创始物种的一个亚种。这一过程§Y每年§!进行一次。\n\n自动人口迁移§Y每月§!进行一次，只在§B机械智能§!或§G合成飞升§!国家进行，且不考虑目标人口的宜居度。\n\n-----------\nMOD版本：§M3.1.0§!\n适配群星版本：§H4.3.X§!"
 xvcv_mdlc_config.1.desc_old: "\n\n全国§R失业人口总量§!：§R[This.xvcv_mdlc_empire_all_unemployed_pops_count_var]§!\n全国可用§G岗位总量§!：§G[This.xvcv_mdlc_empire_all_free_jobs_count_var]§!\n全国可用§B住房总量§!：§B[This.xvcv_mdlc_empire_all_free_housing_count_var]§!"
 xvcv_mdlc_config.1.name: "模组配置：第1页"
 xvcv_mdlc_config.to_credits_page: "§C前往$xvcv_mdlc_config.99.name$§!"
 xvcv_mdlc_config.2.name: "2—设置自定义提示"
 xvcv_mdlc_config.2.desc: "在特定情况下，本模组会向玩家发送通知消息。您可以在这一页中设置它们显示与否。"
 xvcv_mdlc_config.to_page_1: "§C前往$xvcv_mdlc_config.1.name$§!"
 xvcv_mdlc_config.to_page_2: "§C前往$xvcv_mdlc_config.2.name$页面§!"
 xvcv_mdlc_config.to_page_3: "§C前往$xvcv_mdlc_config.3.name$页面§!"
 xvcv_mdlc_config.to_page_4: "§C前往$xvcv_mdlc_config.4.name$页面§!"
 xvcv_mdlc_config.3.name: "3—清理效果"
 xvcv_mdlc_config.3.desc: "用于清理不同模组版本的游戏状态。"
 oxr_mdlc_mod_config_remove_old_ecu_deposits.name: "移除过时的世界型巨械资源点"
 oxr_mdlc_mod_config_remove_old_ecu_deposits.tooltip: "自模组版本3.0.9起，自动服务器与自动熔炉世界不再依赖资源点来提供特定国家修正（例如海军容量区划）。该效果将循环遍历各行星并对其进行清理，确保行星状态焕然一新。\n此效果将立即执行且无需确认。它不会破坏游戏过程，仅会清除那些过时的资源点。"
 xvcv_mdlc_config.4.name: "4—实验性功能"
 xvcv_mdlc_config.99.desc: "制作人员及鸣谢：\n\n—XVCV：本模组原作者，我向他致以感谢\n—Legit-Rikk：重构mute的《Extended Machines》模组，并开发了世界型巨械升级机制\n—FlantingCort、Krukal与鸽组汉化：感谢对本模组中文翻译的维护工作\n\n—Stellaris Modding Den社区的成员们：感谢#modding-help和#moddev-forum频道的技术支持\n—#machine-robots-xpac频道的支持者们：感谢你们的热情参与、头脑风暴，以及在我过度狂想时及时拉回正轨\n—创意工坊活跃用户：感谢你们的反馈与错误报告，我将持续跟进优化\n\n——Openly Retro：感谢他为维护本模组的付出"
 xvcv_mdlc_config.99.name: "模组开发人员与鸣谢"
 xvcv_mdlc_config.message.off.tooltip: "该功能目前§R关闭§!。点击以§G开启§!。"
 xvcv_mdlc_config.message.on.tooltip: "该功能目前§G开启§!。点击以§R关闭§!。"
 xvcv_mdlc_decision_machine_cpu_project.message.off: "§Y$xvcv_mdlc_decision_machine_cpu_project$§!决议完成通知：§R关闭§!"
 xvcv_mdlc_decision_machine_cpu_project.message.on: "§Y$xvcv_mdlc_decision_machine_cpu_project$§!决议完成通知：§G开启§!"
 xvcv_mdlc_decision_machine_ecu_project.message.off: "§Y$xvcv_mdlc_decision_machine_ecu_project$§!决议完成通知：§R关闭§!"
 xvcv_mdlc_decision_machine_ecu_project.message.on: "§Y$xvcv_mdlc_decision_machine_ecu_project$§!决议完成通知：§G开启§!"
 xvcv_mdlc_decision_machine_ser_project.message.off: "§Y$xvcv_mdlc_decision_machine_ser_project$§!决议完成通知：§R关闭§!"
 xvcv_mdlc_decision_machine_ser_project.message.on: "§Y$xvcv_mdlc_decision_machine_ser_project$§!决议完成通知：§G开启§!"
 xvcv_mdlc_decision_virtual_world_project.message.off: "§Y$xvcv_mdlc_decision_virtual_world_project$§!决议完成通知：§R关闭§!"
 xvcv_mdlc_decision_virtual_world_project.message.on: "§Y$xvcv_mdlc_decision_virtual_world_project$§!决议完成通知：§G开启§!"
 xvcv_mdlc_pc_ringworld_automation_project.message.off: "§Y$xvcv_mdlc_pc_ringworld_automation_project$§!决议完成通知：§R关闭§!"
 xvcv_mdlc_pc_ringworld_automation_project.message.on: "§Y$xvcv_mdlc_pc_ringworld_automation_project$§!决议完成通知：§G开启§!"
 xvcv_mdlc_r_unknown_core.message.off: "§Y$xvcv_mdlc_r_unknown_core$§!遗珍通知：§R关闭§!"
 xvcv_mdlc_r_unknown_core.message.on: "§Y$xvcv_mdlc_r_unknown_core$§!遗珍通知：§G开启§!"