from datetime import datetime
from random import randint

AUTOGENERATED_HEADER = f"""
######################################
# AUTOGENERATED on {str(datetime.now())}                #
#                                    #
# DO NOT MAKE CHANGES TO THIS FILE,  #
# AS IT WILL BE OVERWRITTEN          #
# Make sure you are editing the source file
# in the relevant features folder
######################################
"""

FEATURE_NAME = 'compulsory_consolidators'

# Track the maximum deposit size for each game resource (orbital)
ORBITAL_RESOURCES_MAXIMUM_DEPOSIT_SIZES = {
	'alloys': 25,
	'dark_matter': 5,
	'energy': 10,
	'engineering': 10,
	'exotic_gases': 5,
	'food': 10,
	'living_metal': 1,
	'minerals': 10,
	'physics': 10,
	'rare_crystals': 5,
	'society': 10,
	'trade_value': 10,
	'volatile_motes': 5,
	'zro': 5,
}
GAME_RESOURCES_NAMES = ORBITAL_RESOURCES_MAXIMUM_DEPOSIT_SIZES.keys()


MINING_STATION = 'shipclass_mining_station'
RESEARCH_STATION = 'shipclass_research_station'

ORBITAL_DEPOSIT_SHIPCLASS_TYPES = {
	'food': MINING_STATION,
	'energy': MINING_STATION,
	'minerals': MINING_STATION,
	'society_research': RESEARCH_STATION,
	'physics_research': RESEARCH_STATION,
	'engineering_research': RESEARCH_STATION,
	'alloys': MINING_STATION,
	'living_metal': MINING_STATION,
	'rare_crystals': MINING_STATION,
	'exotic_gases': MINING_STATION,
	'volatile_motes': MINING_STATION,
	'sr_zro': RESEARCH_STATION,
	'sr_dark_matter': RESEARCH_STATION,
}

# The deposits are named 'd_zro_deposit_1' but the resource key is 'sr_zro'
GENERAL_RESOURCE_NAMES_TO_GAME_RESOURCES = {
	'trade_value': 'trade',
	'zro': 'sr_zro',
	'dark_matter': 'sr_dark_matter',
	'living_metal': 'sr_living_metal',
	'society': 'society_research',
	'engineering': 'engineering_research',
	'physics': 'physics_research',
}

# For a given game resource, look up how its name would appear in the deposit name
GAME_RESOURCE_NAME_TO_DEPOSIT_NAME = {
	'physics_research': 'physics',
	'engineering_research': 'engineering',
	'society_research': 'society',
	'sr_zro': 'zro_deposit',
	'sr_dark_matter': 'dark_matter_deposit',
	'sr_living_metal': 'living_metal_deposit'
}

def sanity_check():
    return f"Sanity levels at {randint(15,115)}% of normal."
