# Python code to help create effects for the Consolidator civic
import argparse, os, sys

from consolidators_utils import (
	AUTOGENERATED_HEADER,
	FEATURE_NAME,
	GAME_RESOURCES_NAMES,
	ORBITAL_RESOURCES_MAXIMUM_DEPOSIT_SIZES,
	GENERAL_RESOURCE_NAMES_TO_DEPOSIT_NAME,
	sanity_check,
)

###################
# Effect that triggers the special project to summon a mover (once project completes)
###################
def gen_select_orbital_resource_deposits_for_processing_effects():
	"""
oxr_mdlc_planet_select_orbital_energy_deposits_for_processing = {
	switch = {
		trigger = has_deposit
		d_energy_1 = {
			oxr_mdlc_consolidators_planet_make_orbital_energy_deposits_ready_for_extraction = {
				DEPOSIT_SIZE = 1
			}
			remove_deposit = d_energy_1
		}
		d_energy_2 = {
			oxr_mdlc_consolidators_planet_make_orbital_energy_deposits_ready_for_extraction = {
				DEPOSIT_SIZE = 2
			}
			remove_deposit = d_energy_2
		}
	}
}
	"""
	effect_open = """
oxr_mdlc_planet_select_orbital_{game_resource}_deposits_for_processing = {{
	switch = {{
		trigger = has_deposit"""
	
	effect_close = """
	}
}
"""
	# This effect triggers the special project
	orbital_deposit_select_effect_wrapper = """
		d_{game_resource}_{series} = {{
			oxr_mdlc_consolidators_planet_make_orbital_{game_resource}_deposits_ready_for_extraction = {{
				DEPOSIT_SIZE = {series}
			}}
			remove_deposit = d_{converted_resource_name}_{series}
		}}"""

	select_orbital_effects_list = []

	for game_resource in GAME_RESOURCES_NAMES:

		resource_effect_open = effect_open.format(game_resource=game_resource)
		deposit_switch_effects = []

		max_deposit_size = ORBITAL_RESOURCES_MAXIMUM_DEPOSIT_SIZES[game_resource]
		for deposit_size in range(0,max_deposit_size):
			converted_resource_name = GENERAL_RESOURCE_NAMES_TO_DEPOSIT_NAME.get(
				game_resource, game_resource
			)

			single_deposit_switch_effect = orbital_deposit_select_effect_wrapper.format(
				game_resource=game_resource,
				# Add 1 to the deposit_size var because d_energy_0 isn't valid
				series=deposit_size+1,
				converted_resource_name=converted_resource_name
			)
			deposit_switch_effects.append(single_deposit_switch_effect)

		self_contained_effect_for_resource = f"""
{resource_effect_open}
{"\n".join(deposit_switch_effects)}
{effect_close}
"""
		select_orbital_effects_list.append(self_contained_effect_for_resource)

	return {
		'contents': "".join(select_orbital_effects_list),
		'count': len(select_orbital_effects_list)
	}


##################
# Activate special project at planet, after event option has been selected
##################
def gen_make_orbital_resource_deposits_ready_for_extraction():
	"""
	oxr_mdlc_consolidators_planet_make_orbital_energy_deposits_ready_for_extraction = {

		set_planet_flag = oxr_mdlc_consolidators_planet_has_available_energy_consolidation

		# Find the deposit of the associated type, and increment a var
		set_or_increment_variable = {
			VAR = oxr_mdlc_consolidator_orbital_resource_type_energy
			AMOUNT = $DEPOSIT_SIZE$
		}

		enable_special_project = {
			name = "OXR_MDLC_CONSOLIDATE_ENERGY"
			location = this
			owner = space_owner
		}
	}
	
	For each resource, generate the above effect
	"""
	effect = """
oxr_mdlc_consolidators_planet_make_orbital_{game_resource}_deposits_ready_for_extraction = {{

	set_planet_flag = oxr_mdlc_consolidators_planet_has_available_{game_resource}_consolidation
	set_or_increment_variable = {{
		VAR = oxr_mdlc_consolidator_orbital_resource_type_{game_resource}
		AMOUNT = $DEPOSIT_SIZE$
	}}
	enable_special_project = {{
		name = "OXR_MDLC_CONSOLIDATE_{game_resource}"
		location = this
		owner = space_owner
	}}

}}
"""
	orbital_project_effects_list = []
	for game_resource in GAME_RESOURCES_NAMES:
		rendered_effect = effect.format(
			game_resource=game_resource
		)
		orbital_project_effects_list.append(rendered_effect)

	return {
		'contents': "\n".join(orbital_project_effects_list),
		'count': len(orbital_project_effects_list)
	}

def make_orbital_extract_scripted_effects_file_data():
	# One file for these autogenerated effects
	first_part = gen_make_orbital_resource_deposits_ready_for_extraction()
	second_part = gen_select_orbital_resource_deposits_for_processing_effects()
	return {
		'filename': "50_oxr_mdlc_scripted_effects_consolidators_orbital_extraction.txt",
		'contents': f"""
#
# Trigger special projects from the event menu, for selected resource type
#
{first_part['contents']}
#
# Summon ship to transport the deposit value, after special project completion
#
{second_part['contents']}
""",
		'count': first_part['count'] + second_part['count']
	}


def do_all_work(feature_folder):
	# Write our effects to the FEATURES folder and not the mod's base 'common/scripted_effects' folder
    scripted_effect_data = make_orbital_extract_scripted_effects_file_data()
    feature_scripted_effects_folder = os.path.join(
    	feature_folder, FEATURE_NAME, 'common', 'scripted_effects'
    )

    with open(
        os.path.join(
        	feature_scripted_effects_folder,
        	scripted_effect_data['filename']
        ), 'wb'
    ) as outfile:
        outfile.write(AUTOGENERATED_HEADER.encode('utf-8'))
        outfile.write(scripted_effect_data['contents'].encode('utf-8'))
        print(f"\nCompiled {scripted_effect_data['count']} EFFECTS in {scripted_effect_data['filename']}")

    print(sanity_check())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="0xRetro Compulsory Consolidator effects code",
    )
    parser.add_argument(
        "--feature-folder",
        dest="feature_folder",
        help="Absolute path to 'mrec_tools/features'. (Required)",
        required=True
    )
    if not os.path.abspath(
        'feature_folder'
    ):
        sys.exit(
            "Couldn't find the features folder where you said it was.\n"
            "Run with --feature-folder /home/users/you/location/of/feature_folder"
        )
    args = parser.parse_args()
    do_all_work(args.feature_folder)
