""" Find missing deposits in series and generate blank placeholder ones that can't spawn """
from consolidators_utils import (
	AUTOGENERATED_HEADER,
	FEATURE_NAME,
	MINING_STATION,
	RESEARCH_STATION,
	sanity_check,
)

import argparse, os, sys

"""

dark matter: missing 4-9
alloys: missing 6-10, 11-24
food: missing 1-2,7-9
"""

MISSING_RANGES = {
	'sr_dark_matter': [(4,9+1)],
	'alloys': [
		(6,10+1), (11,24+1)
	],
	'food': [
		(1,2+1), (7,9+1)
	]
}
GAME_RESOURCE_NAMES_TO_DEPOSIT_NAMES = {
	'sr_dark_matter': 'dark_matter_deposit',
}
ORBITAL_DEPOSIT_ECONOMIC_CATEGORIES = {
	'sr_dark_matter': 'orbital_research_deposits',
	'food': 'orbital_mining_deposits',
	'alloys': 'orbital_mining_deposits',
}
ORBITAL_DEPOSIT_SHIPCLASSES = {
	'sr_dark_matter': 'shipclass_research_station',
	'food': 'shipclass_mining_station',
	'alloys': 'shipclass_mining_station',
}
ORBITAL_DEPOSIT_ICONS = {
	'sr_dark_matter': 'unused/d_strategic_resources',
	'alloys': 'unused/d_ruined_system',
	'food': None
}

# We don't actually want these deposits to spawn in the game
# But they could be placed by us
orbital_deposit_template = """
d_{deposit_resource_name}_{series} = {{
	{deposit_icon_statement}
	resources = {{
		category = {deposit_category}
		produces = {{
			{game_resource} = {series}
		}}
	}}
	station = {deposit_shipclass}
	is_for_colonizable = no
	potential = {{ always = no }}
	drop_weight = {{ weight = 0 }}
}}

"""

def iterate_resources_ranges_make_deposits():

	deposits_list = []

	resource_names = MISSING_RANGES.keys()
	for game_resource in resource_names:

		# Go through each range, and sequentially generate code for deposits
		for missing_range_tuple in MISSING_RANGES[game_resource]:

			for deposit_size in range(
				missing_range_tuple[0], missing_range_tuple[1]
			):
				deposit_icon_statement = f"icon = \"{ORBITAL_DEPOSIT_ICONS.get(game_resource)}\"" if ORBITAL_DEPOSIT_ICONS.get(game_resource) else ""
				deposit_code = orbital_deposit_template.format(
					# If the deposit name is different, look it up, otherwise use the resource name
					deposit_resource_name=GAME_RESOURCE_NAMES_TO_DEPOSIT_NAMES.get(
						game_resource, game_resource
					),
					game_resource=game_resource,
					series=deposit_size,
					deposit_icon_statement=deposit_icon_statement,
					deposit_category=ORBITAL_DEPOSIT_ECONOMIC_CATEGORIES[game_resource],
					deposit_shipclass=ORBITAL_DEPOSIT_SHIPCLASSES[game_resource]
				)
				deposits_list.append(deposit_code)

	return {
		'filename': '55_oxr_mdlc_filler_deposits_compulsory_consolidator.txt',
		'contents': f"""
{"\n".join(deposits_list)}
""",
		'count': len(deposits_list)
	}

def do_all_work(feature_folder):
	# Write our effects to the DEPOSITS folder and not the mod's base 'common/scripted_effects' folder
    deposits_data = iterate_resources_ranges_make_deposits()
    feature_deposits_folder = os.path.join(
    	feature_folder, FEATURE_NAME, 'common', 'deposits'
    )

    with open(
        os.path.join(
        	feature_deposits_folder,
        	deposits_data['filename']
        ), 'wb'
    ) as outfile:
        outfile.write(AUTOGENERATED_HEADER.encode('utf-8'))
        outfile.write(deposits_data['contents'].encode('utf-8'))
        print(f"\nCompiled {deposits_data['count']} DEPOSITS in {deposits_data['filename']}")

    print(sanity_check())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="0xRetro Compulsory Consolidator DEPOSITS code",
    )
    parser.add_argument(
        "--feature-folder",
        dest="feature_folder",
        help="Absolute path to 'mrec_tools/features'. (Required)",
        required=True
    )
    if not os.path.abspath(
        'feature_folder'
    ):
        sys.exit(
            "Couldn't find the features folder where you said it was.\n"
            "Run with --feature-folder /home/users/you/location/of/feature_folder"
        )
    args = parser.parse_args()
    do_all_work(args.feature_folder)
