""" Make triggers to detect orbital and planetary deposits """
from typing import List
from consolidators_utils import (
    GameResource,
    AUTOGENERATED_HEADER,
    FEATURE_NAME,
    sanity_check,
)
import os
from json import load as json_load
import argparse

THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))


def gen_trigger_check_planet_has_orbital_deposit_of_type(
    deposit_resource_name: str,
    deposits_list: List[str]
):
    """ note that 'deposit_resource_name' may be different than the resource name 
    related to what it's producing, ex:
    `d_trade_value_1` produces `trade`, not `trade_value`
    """

    trigger_structure = """
oxr_mdlc_consolidators_planet_has_orbital_{resource}_deposits = {{
    OR = {{
{has_deposit_triggers_list}
    }}
}}
"""
    has_deposit_triggers_list = []
    for deposit in deposits_list:
        has_deposit_triggers_list.append(
            "has_deposit = {deposit}"
        )
    return trigger_structure.format(
        resource=deposit_resource_name,
        has_deposit_triggers_list="     \n".join(has_deposit_triggers_list)
    )


def gen_orbital_resource_triggers_file_contents(
    deposit_categories_root: dict
):
    """
    Iterate over a data structure holding multiple sets of orbital deposit groups,
    and create all their triggers

    deposit_categories_root has:

    'planetary_deposits'
    'orbital_mining_deposits'
    'orbital_research_deposits'

    from deposit_categories.json """

    specific_checks_for_orbital_mining_deposits_resources = []
    specific_checks_for_orbital_research_deposits_resources = []

    resource_category_trigger_name = "oxr_mdlc_consolidators_planet_has_orbital_{resource}_deposits"
    resource_category_trigger_checks = []


    """ These two triggers check if a planet has either orbital mining or research deposits """
    orbital_mining_category_trigger_check = """
oxr_mdlc_consolidators_planet_has_orbital_mining_deposits = {{
    OR = {{
        {orbital_mining_category_trigger_check_list}
    }}
}}
"""
    orbital_research_category_trigger_check = """
oxr_mdlc_consolidators_planet_has_orbital_research_deposits = {{
    OR = {{
        {orbital_research_category_trigger_check_list}
    }}
}}
"""

    # This is the top-level trigger checking if there are any orbital deposits at all
    # of any category
    planet_has_any_orbital_deposits_trigger = """
oxr_mdlc_consolidators_planet_has_orbital_deposits = {{
    OR = {{
        {resource_category_trigger_checks}
    }}
}}
"""

    scripted_triggers_for_deposit_detection = """
# Mining deposit triggers
{orbital_mining_category_trigger_check}
{specific_checks_for_orbital_mining_deposits_resources}

# Research deposit triggers
{orbital_research_category_trigger_check}
{specific_checks_for_orbital_research_deposits_resources}
"""

    # We need to know which of the keys in deposits_categories.json are orbital-related
    orbital_type_keys = ['orbital_mining_deposits', 'orbital_research_deposits']

    """ Build all the has_orbital_<resource>_deposits = yes """
    for orbital_type_key in orbital_type_keys:
        # Look up all the resources in 'orbital_mining_deposits' for example,
        # and iterate each resource and its related deposit names

        for resource_name_key in deposit_categories_root[orbital_type_key].keys():

            specific_checks_for_orbital_resource_types = []

            # This will end up iterating all of the mining and research orbital categories,
            # so that 'oxr_mdlc_consolidators_planet_has_orbital_deposits' includes checks for both
            # types of orbital resource
            # <trigger> = yes
            resource_category_trigger_checks.append(
                resource_category_trigger_name.format(
                    resource=resource_name_key
                )
            )
            # Code for the orbital_resource trigger, which exists independently
            orbital_resource_trigger = gen_trigger_check_planet_has_orbital_deposit_of_type(
                deposit_resource_name=resource_name_key,
                deposits_list=deposit_categories_root[orbital_type_key][resource_name_key]
            )
            # Since we are iterating resources, build each individual set of orbital type checks
            if orbital_type_key == 'orbital_mining_deposits':
                specific_checks_for_orbital_mining_deposits_resources.append(orbital_resource_trigger)
            elif orbital_type_key == 'orbital_research_deposits':
                specific_checks_for_orbital_research_deposits_resources.append(orbital_resource_trigger)


    # Put the file all together, why not
    # This should print out 'oxr_mdlc_consolidators_planet_has_orbital_deposits'
    # and all the other triggers that check for specific orbital resource types
    file_contents = specific_checks_for_orbital_mining_resources.format(
        resource_category_trigger_checks="      \n".join(resource_category_trigger_checks),
        specific_checks_for_orbital_mining_deposits_resources="\n".join(specific_checks_for_orbital_mining_deposits_resources),
        specific_checks_for_orbital_research_deposits_resources="\n".join(specific_checks_for_orbital_research_deposits_resources)
    )
    return file_contents


def make_compulsory_consolidators_deposit_detection_file_data(deposits_categories: dict):

    contents = gen_orbital_resource_triggers_file_contents(deposit_categories_root=deposits_categories)

    return {
        'filename': "40_oxr_mdlc_scripted_triggers_consolidators_deposit_detection.txt",
        'contents': contents,
    }


def do_all_work(feature_folder):
    # Write our effects to the FEATURES folder and not the mod's base 'common/scripted_effects' folder

    with open(
        os.path.join(THIS_FOLDER, 'deposits_categories.json')
    ) as deposits_categories_source_file:

        deposits_categories_data = json_load(deposits_categories_source_file)


    scripted_triggers_data = make_compulsory_consolidators_deposit_detection_file_data(deposits_categories_data)
    scripted_triggers_folder = os.path.join(
        feature_folder, FEATURE_NAME, 'common', 'scripted_triggers'
    )

    with open(
        os.path.join(
            scripted_triggers_folder,
            scripted_triggers_data['filename']
        ), 'wb'
    ) as outfile:
        outfile.write(AUTOGENERATED_HEADER.encode('utf-8'))
        outfile.write(scripted_triggers_data['contents'].encode('utf-8'))
        print(f"\nCompiled {scripted_triggers_data['filename']}")

    print(sanity_check())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="0xRetro Compulsory Consolidator SCRIPTED TRIGGERS (ORBITAL DEPOSITS) code",
    )
    parser.add_argument(
        "--feature-folder",
        dest="feature_folder",
        help="Absolute path to 'mrec_tools/features'. (Required)",
        required=True
    )
    if not os.path.abspath(
        'feature_folder'
    ):
        sys.exit(
            "Couldn't find the features folder where you said it was.\n"
            "Run with --feature-folder /home/users/you/location/of/feature_folder"
        )
    args = parser.parse_args()
    do_all_work(args.feature_folder)
