from consolidators_utils import (
	AUTOGENERATED_HEADER,
	FEATURE_NAME,
	GAME_RESOURCES_NAMES,
	GENERAL_RESOURCE_NAMES_TO_GAME_RESOURCES,
	sanity_check,
)

import argparse, os, sys

special_project_template = """
special_project = {{
	key = "OXR_MDLC_CONSOLIDATE_{game_resource}"
	days_to_research = 15
	tech_department = engineering_technology
	icon = "gfx/interface/icons/situation_log/situation_log_quest.dds"
	picture = GFX_evt_atmospheric_flight
	location = yes

	event_scope = ship_event

	requirements = {{ shipclass_constructor = 1 }}

	on_success = {{
		# from = planet the project is at
		from = {{
			oxr_mdlc_country_create_mover_fleet_give_instructions = {{
				RESOURCE = {game_resource_name_mapped}
			}}
		}}
	}}

	on_fail = {{ }}
	abort_trigger = {{ }}
}}
"""

def make_orbital_extract_special_projects_file_data():
	# One file for these autogenerated effects
	special_projects_list = []
	for game_resource in GAME_RESOURCES_NAMES:
		special_project_for_resource = special_project_template.format(
			game_resource=game_resource,
			game_resource_name_mapped=GENERAL_RESOURCE_NAMES_TO_GAME_RESOURCES.get(
				game_resource, game_resource
			)
		)
		special_projects_list.append(special_project_for_resource)


	return {
		'filename': "57_oxr_mdlc_special_projects_consolidators_orbital_extraction.txt",
		'contents': "\n".join(special_projects_list)
	}

def do_all_work(feature_folder):
# Write our effects to the FEATURES folder and not the mod's base 'common/scripted_effects' folder
    special_projects_data = make_orbital_extract_special_projects_file_data()
    special_projects_folder = os.path.join(
    	feature_folder, FEATURE_NAME, 'common', 'special_projects'
    )
    num_projects_compiled = special_projects_data['contents'].count('special_project')
    with open(
        os.path.join(
        	special_projects_folder,
        	special_projects_data['filename']
        ), 'wb'
    ) as outfile:
        outfile.write(AUTOGENERATED_HEADER.encode('utf-8'))
        outfile.write(special_projects_data['contents'].encode('utf-8'))
        print(f"\nCompiled {num_projects_compiled} PROJECTS in {special_projects_data['filename']}")

    print(sanity_check())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="0xRetro Compulsory Consolidator SPECIAL PROJECTS code",
    )
    parser.add_argument(
        "--feature-folder",
        dest="feature_folder",
        help="Absolute path to 'mrec_tools/features'. (Required)",
        required=True
    )
    if not os.path.abspath(
        'feature_folder'
    ):
        sys.exit(
            "Couldn't find the features folder where you said it was.\n"
            "Run with --feature-folder /home/users/you/location/of/feature_folder"
        )
    args = parser.parse_args()
    do_all_work(args.feature_folder)
