""" Specifically generate event 3000

# planet dialogue to consolidate resources
# 'from' is the source planet
country_event = {
	id = oxr_mdlc_civic_consolidators.3000
	title = "oxr_mdlc_civic_consolidators.3000.title"
	desc = "oxr_mdlc_civic_consolidators.3000.desc"
	picture = GFX_evt_habitable_dig_site
	is_triggered_only = yes

	# energy
	option = {
		name = "oxr_mdlc_civic_consolidators.3000.option_energy"
		allow = {
			from = {
				oxr_mdlc_consolidators_planet_has_orbital_energy_deposits = yes
				NOT = {
					has_planet_flag = oxr_mdlc_consolidators_planet_consolidation_in_progress
				}
			}
		}
		hidden_effect = {
			log = "Planet menu picked energy deposits for processing"
			from = {
				oxr_mdlc_planet_select_orbital_energy_deposits_for_processing = yes
			}
		}
	}

	option = {
		name = EXCELLENT
		default_hide_option = yes
	}
}
"""
import argparse, os
from consolidators_utils import (
	AUTOGENERATED_HEADER,
	FEATURE_NAME,
	GAME_RESOURCES_NAMES,
	sanity_check,
)

event_header = """
namespace = oxr_mdlc_civic_consolidators

country_event = {
	id = oxr_mdlc_civic_consolidators.3000
	title = "oxr_mdlc_civic_consolidators.3000.title"
	desc = "oxr_mdlc_civic_consolidators.3000.desc"
	picture = GFX_evt_habitable_dig_site
	is_triggered_only = yes

"""
event_footer = """

}
"""

event_resource_option = """
	# {game_resource}
	option = {{
		name = "oxr_mdlc_civic_consolidators.3000.option_{game_resource}"
		trigger = {{
			from = {{
				oxr_mdlc_consolidators_planet_has_orbital_{game_resource}_deposits = yes
			}}
		}}
		allow = {{
			from = {{
				NOT = {{
					has_planet_flag = oxr_mdlc_consolidators_planet_consolidation_in_progress
				}}
			}}
		}}
		hidden_effect = {{
			log = "Planet menu picked {game_resource} deposits for processing"
			from = {{
				oxr_mdlc_planet_select_orbital_{game_resource}_deposits_for_processing = yes
			}}
		}}
	}}
"""

def generate_event_options():

	event_options_list = []
	for game_resource in GAME_RESOURCES_NAMES:

		event_options_list.append(
			event_resource_option.format(
				game_resource=game_resource
			)
		)

	event_contents = f"""
{event_header}
{"".join(event_options_list)}
{event_footer}
"""

	return {
		'filename': "75_oxr_mdlc_events_compulsory_consolidators_orbital_extraction_menu.txt",
		'contents': event_contents,
		'count': len(event_options_list)
	}

def do_all_work(feature_folder):
	# Write our effects to the EVENT folder and not the mod's base 'common/scripted_effects' folder
    event_code = generate_event_options()
    feature_events_folder = os.path.join(
    	feature_folder, FEATURE_NAME, 'events'
    )

    with open(
        os.path.join(
        	feature_events_folder,
        	event_code['filename']
        ), 'wb'
    ) as outfile:
        outfile.write(AUTOGENERATED_HEADER.encode('utf-8'))
        outfile.write(event_code['contents'].encode('utf-8'))
        print(f"\nCompiled {event_code['count']} EVENT OPTIONS in {event_code['filename']}")

    print(sanity_check())

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="0xRetro Compulsory Consolidator EVENTS code",
    )
    parser.add_argument(
        "--feature-folder",
        dest="feature_folder",
        help="Absolute path to 'mrec_tools/features'. (Required)",
        required=True
    )
    if not os.path.abspath(
        'feature_folder'
    ):
        sys.exit(
            "Couldn't find the features folder where you said it was.\n"
            "Run with --feature-folder /home/users/you/location/of/feature_folder"
        )
    args = parser.parse_args()
    do_all_work(args.feature_folder)
