""" Merge files in sub-folders into the mod's main files """

from datetime import datetime
import sys, os

""" Allowed names for subfolders """
GAME_FOLDER_NAMES = (
    'common', 'gfx', 'interface', 'events', 'localisation',
    'flags', 'prescripted_countries'
)

AUTOGENERATED_HEADER = f"""
######################################
# AUTOGENERATED on {str(datetime.now())}                #
#                                    #
# DO NOT MAKE CHANGES TO THIS FILE,  #
# AS IT WILL BE OVERWRITTEN          #
# Make sure you are editing the source file
# in the relevant features folder
######################################
"""
