""" Merge files in sub-folders into the mod's main files

This should be run from the mod's main folder, like so:

    python mrec_tools/features/sync.py

"""

import argparse
import subprocess
from datetime import datetime
import sys, os
from typing import List
from time import perf_counter

MOD_MAIN_PATH = os.getcwd()

""" Big blob of text warning modders that the file was 
copied from a feature, and don't edit it """
AUTOGENERATED_HEADER = f"""
######################################
# AUTOGENERATED on {str(datetime.now())}                #
#                                    #
# DO NOT MAKE CHANGES TO THIS FILE,  #
# AS IT WILL BE OVERWRITTEN          #
# Make sure you are editing the source file
# in the relevant features folder
######################################
"""

def get_feature_folders(feature_folder_base_path) -> List[str]:
    """ Look inside features folder to see what subfolders are there """
    return [
        f.path for f in os.scandir(feature_folder_base_path)
        if f.is_dir()
    ]

def copy_file_ignore_same(src, dest, *, follow_symlinks=True):
    """ Write the autogenerated header text to the file when copying """
    # with open("w", dest) as destfile:
        # with open("r", src) as srcfile:
    1
    # TODO later ... save my brain

def sync_feature_folder_to_main_mod(feature_folder_path):
    """ Sync a single feature folder to the main mod """
    content_folders_list = [
        f.path for f in os.scandir(feature_folder_path)
        if f.is_dir()
    ]
    subprocess.run(
        [
            "rsync",
            "-rvuzq",
            f"{feature_folder_path}/",
            MOD_MAIN_PATH
        ],
        check=True
    )
    print(f"\n\033[92m+ Finished syncing {feature_folder_path} to the main mod.\033[0m")

if __name__== "__main__":
    """ Check that the command is run in the correct location """
    if not os.path.isdir(
        'mrec_tools'
    ):
        sys.exit(
            "Run this command from the mod's base folder. "
        )

    features_folder = os.path.join(
        MOD_MAIN_PATH, 'mrec_tools', 'features'
    )
    start_time = perf_counter()
    parser = argparse.ArgumentParser(
        prog="0xRetro MRE:C Feature Sync Tool",
        description="Sync a game feature from its separate code folder to the main mod. Sync all (default, optional) or a specific folder"
    )
    parser.add_argument(
        "--features",
        nargs="+",
        dest="features_to_sync",
        help="Any feature folders you want to sync to the main mod, separated by spaces. (Optional)",
        default=[]
    )
    args = parser.parse_args()
    # Now that's out of the way
    print("*~~ 0xRetro MRE:C Feature Sync Tool ~~*\n")
    print(
        "This tool syncs any or all game features in the 'features' folder, from its separate code folder to the main mod. "
        "Because we like to stay organized here.\n"
    )
    if not len(args.features_to_sync):
        """ Sync all to the main mod """
        feature_folders_to_sync = [
            f.path for f in os.scandir(features_folder)
            if f.is_dir()
        ]
        for folder_path in feature_folders_to_sync:
            sync_feature_folder_to_main_mod(folder_path)
        print(
            "Done syncing all feature folders to the main mod. "
            "Remember to check for errors.."
        )
    else:
        """ Modder has specified one or more folders to sync .. check if any are mistyped """
        for desired_feature_folder in args.features_to_sync:
            if not os.path.isdir(
                os.path.join(features_folder, desired_feature_folder)
            ):
                sys.exit(
                    f"Did not find a feature folder named {desired_feature_folder}. "
                    "Insert coin, try again"
                )
        # Now sync them since they exist
        for desired_feature_folder in args.features_to_sync:
            feature_folder_path = os.path.join(
                features_folder, desired_feature_folder
            )
            sync_feature_folder_to_main_mod(feature_folder_path)

    # Boast, or cry, about how fast this script is
    end_time = perf_counter()
    execution_time = end_time - start_time
    print(f"\nDone in {str(execution_time)[:5]} seconds.")
